### PR TITLE
Fix pegasus service

### LINKED ISSUE #746: [BUG] Gaia executor servers [0, 1] are not connected.
**Describe the bug**
Gaia exectors cannot connect to each other when running GraphScope on kubernetes with multiple workers.

**To Reproduce**
```python
import graphscope
graphscope.set_option(show_log=True)

sess = graphscope.session(
        num_workers=2,
        enable_gaia=True,
        # other session params
)

graph = sess.g()

interactive = sess.gremlin(graph)
```

Errors in `executor log`

```
GraphScope/research/gaia/pegasus/server/src/service.rs:54) [tokio-runtime-worker] job[121] get error Build job failure: server error: servers [0, 1] are not connected;
```

### PR DESCRIPTION
**Pull request by shirly121**
## Related issue number

Fixes #746

### CODE REVIEW

File: interactive_engine/src/executor/gaia_runtime/src/server/manager.rs [hunk 1]
```diff
@@ -218,7 +218,7 @@ fn parse_store_ip_list_for_gaia(address_list: &[RuntimeAddressProto]) -> Vec<Pee
             server_id: server_idx,
             ip: address.get_ip().to_string(),
             // assign a random port for pegasus
-            port: 0,
+            port: 8198,
```
Comment (lidongze0629) [inline interactive_engine/src/executor/gaia_runtime/src/server/manager.rs:221]: Fixed port of multiple instances will conflict in local mode?

Comment (acezen) [reply interactive_engine/src/executor/gaia_runtime/src/server/manager.rs:221]: maybe we should have a config file to specify the port?

**Review by sighingnow — APPROVED** [review]
LGTM.
