### PR TITLE
Fixes bugs while building on macOS 12 wiht apple silicon

### LINKED ISSUE #1734: [BUG] Install deps and build on macOS failed.
**Describe the bug**
install deps on macOS failed.

```shell
[ 50%] Linking CXX shared library ../../shared-lib/libvineyard_malloc.dylib
[ 50%] Built target vineyard_malloc
[ 50%] Building CXX object modules/migrate/CMakeFiles/vineyard-migrate.dir/vineyard_migrate.cc.o
[ 51%] Building CXX object modules/basic/CMakeFiles/vineyard_basic.dir/ds/tensor.cc.o
1 warning generated.
[ 52%] Building CXX object CMakeFiles/_C.dir/python/error.cc.o
[ 52%] Building CXX object CMakeFiles/_C.dir/python/pybind11_utils.cc.o
1 warning generated.
[ 52%] Building CXX object modules/migrate/CMakeFiles/vineyard-migrate-stream.dir/vineyard_migrate_stream.cc.o
1 warning generated.
[ 52%] Building CXX object modules/basic/CMakeFiles/vineyard_basic.dir/ds/types.cc.o
[ 53%] Building CXX object modules/basic/CMakeFiles/vineyard_basic.dir/stream/byte_stream.cc.o
[ 53%] Building CXX object CMakeFiles/_C.dir/python/vineyard.cc.o
[ 54%] Linking CXX executable ../../bin/vineyard-migrate
[ 54%] Built target vineyard-migrate
[ 54%] Building CXX object modules/basic/CMakeFiles/vineyard_basic.dir/stream/dataframe_stream.cc.o
[ 56%] Building CXX object modules/basic/CMakeFiles/vineyard_basic.dir/stream/parallel_stream.cc.o
[ 56%] Building CXX object modules/basic/CMakeFiles/vineyard_basic.dir/stream/recordbatch_stream.cc.o
[ 57%] Linking CXX shared module shared-lib/_C.cpython-39-darwin.so
[ 58%] Linking CXX executable ../../bin/vineyard-migrate-stream
[ 58%] Built target vineyard-migrate-stream
[ 58%] Copying the migration artifacts to the python package.
[ 58%] Built target vineyard_migrate_python
/opt/homebrew/opt/llvm/bin/llvm-strip: error: unsupported load command (cmd=0x80000034)
make[2]: *** [shared-lib/_C.cpython-39-darwin.so] Error 1
make[2]: *** Deleting file `shared-lib/_C.cpython-39-darwin.so'
make[1]: *** [CMakeFiles/_C.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
1 warning generated.
[ 58%] Linking CXX shared library ../../shared-lib/libvineyard_basic.dylib
[ 58%] Built target vineyard_basic
1 warning generated.
[ 58%] Linking CXX static library ../Binaries/libcpprest.a
[ 58%] Built target cpprest
make: *** [all] Error 2
```

**To Reproduce**
- ./scripts/install_deps.sh --dev

**Environment (please complete the following information):**
 - GraphScope version: master
 - OS: macOS 12.4 with m1 pro
 - Python: 3.9 Arm64

### PR DESCRIPTION
**Pull request by waruto210**
## What do these changes do?

add new vineyard version which can build on MacOS with LLVM<=14, find `homebrew_prefix` in `install_cppkafka()`, disable build tests and examples in `install_cppkafka()`, which can not compile on macOS.

## Related issue number

Resolves #1734

### CODE REVIEW

**Comment by waruto210** [comment]
@sighingnow Can you take a brief look.

File: scripts/install_deps.sh [hunk 1]
```diff
@@ -17,6 +17,9 @@ readonly GRAPE_BRANCH="master" # libgrape-lite branch
 readonly V6D_VERSION="0.5.0"  # vineyard version
 readonly V6D_BRANCH="v0.5.0" # vineyard branch
 
+# readonly V6D_VERSION="0.5.2"  # vineyard version for LLVM<=14 on MacOS 
+# readonly V6D_BRANCH="v0.5.2" # vineyard branch for LLVM<=14 on MacOS
```
Comment (sighingnow) [inline scripts/install_deps.sh:21]: You could update the `0.5.0` to `0.5.2` directly. Its safe for such a upgrade.

File: scripts/install_deps.sh [hunk 2]
```diff
@@ -507,8 +510,14 @@ install_cppkafka() {
...
-    export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
-    export CPPFLAGS="-I/usr/local/opt/openssl@3/include"
+    if [[ "$(uname -m)" == *"x86_64"* ]]; then
+      declare -r homebrew_prefix=/usr/local
+    else
+      # Apple Silicon: packages are installed under /opt/homebrew by default
+      declare -r homebrew_prefix=/opt/homebrew
+    fi
+    export LDFLAGS="-L${homebrew_prefix}/opt/openssl@3/lib"
+    export CPPFLAGS="-I${homebrew_prefix}/opt/openssl@3/include"
```
Comment (sighingnow) [inline scripts/install_deps.sh:520]: The homebrew prefix can be abtained by `$(brew --prefix)`.

File: scripts/install_deps.sh [hunk 3]
```diff
@@ -517,7 +526,7 @@ install_cppkafka() {
   pushd /tmp/cppkafka
   git submodule update --init
   mkdir -p build && pushd build
-  cmake .. && make -j$(nproc)
+  cmake -DCPPKAFKA_DISABLE_TESTS=ON  -DCPPKAFKA_DISABLE_EXAMPLES=ON .. && make -j$(nproc)
```
Comment (sighingnow) [inline scripts/install_deps.sh:529]: Nice catch!

**Review by sighingnow — APPROVED** [review]
Basically LGTM. Just some minor comments.

**Comment by waruto210** [comment]
> Basically LGTM. Just some minor comments.

fixed

**Review by lidongze0629 — APPROVED** [review]
