### PR TITLE
[Bug Fix] Avoid throwing exception after processing grpc error from executor in compiler

### LINKED ISSUE #2181: [BUG] GIE-Compiler throw `NullPointer` exception when receiving grpc error from executor
**Describe the bug**
as titled.
**To Reproduce**
steps:
1. start executor by executing `cd GraphScope/interactive_engine/executor/ir && RUST_LOG=info ./target/release/start_rpc_server --config ./integrated/config`
2. start compiler by executing `cd GraphScope/interactive_engine/compiler && make run`
3. in gremlin console, run `g.V().values("name").out()` which is invalid and can trigger an error from executor, and then compiler will throw a `NullPointer` exception.
image

### PR DESCRIPTION
**Pull request by shirly121**
… in compiler

## What do these changes do?
as titled.

## Related issue number

Fixes #2181

### CODE REVIEW

File: interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/client/RpcBroadcastProcessor.java [hunk 1]
```diff
@@ -54,10 +54,9 @@ public void broadcast(PegasusClient.JobRequest request, ResultProcessor processo
                 processor.process(response);
             }
             processor.finish();
-        } catch (Exception e) {
+        } catch (Throwable e) {
             logger.error("broadcast exception {}", e);
```
Comment (longbinlai) [inline interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/client/RpcBroadcastProcessor.java:58]: Please add more details for the log.

**Review by longbinlai — APPROVED** [review]
