### PR TITLE
Fix predicate

### LINKED ISSUE #286: [Gremlin] The predicate in where()/has() step returns wrong result
**Describe the bug**
Some queries produce the wrong results, not consistent with the expected.

**To Reproduce**
1. g.V().as("a").out("created").where(__.as("a").values("name").is("josh")).in("created").values("name")
2. g.V().has("age", P.without(27))
3. g.V().as("a").out("created").in("created").as("b").where("a", P.gt("b")).by("age").select("a", "b").by("name")

Expected:
1. 
==>marko
==>josh
==>peter
==>josh

2.
==>v[1]
==>v[4]
==>v[6]

3.
==>{a=josh, b=marko}
==>{a=peter, b=marko}
==>{a=peter, b=josh}

Actual:
1. Empty
2. Not support
3. Wrong result:
==>{a=marko, b=josh}
==>{a=marko, b=peter}
==>{a=josh, b=peter}

### PR DESCRIPTION
**Pull request by BingqingLyu**
## Related issue number

Fixes #286

### CODE REVIEW

File: research/gaia/gremlin/gremlin_core/src/structure/filter/codec.rs [hunk 1]
```diff
@@ -85,6 +86,47 @@ pub fn pb_value_to_object(raw: &pb_type::Value) -> Option<Object> {
...
 }
 
+pub fn pb_value_to_array_object(raw: &pb_type::Value) -> Option<HashSet<Object>> {
+    match &raw.item {
+        Some(pb_type::value::Item::Blob(_))
+        | Some(pb_type::value::Item::Boolean(_))
+        | Some(pb_type::value::Item::I32(_))
+        | Some(pb_type::value::Item::I64(_))
+        | Some(pb_type::value::Item::F64(_))
+        | Some(pb_type::value::Item::Str(_)) => unimplemented!(),
```
Comment (longbinlai) [inline research/gaia/gremlin/gremlin_core/src/structure/filter/codec.rs:96]: These unimplemented stuff is not so hard to fix.

File: research/gaia/gremlin/gremlin_core/src/structure/filter/codec.rs [hunk 2]
```diff
@@ -214,8 +256,48 @@ fn lte(left: &pb_type::Key, right: &pb_type::Value) -> Result<ElementFilter, Par
...
-fn with_in(_left: &pb_type::Key, _right: &pb_type::Value) -> Result<ElementFilter, ParseError> {
-    unimplemented!()
+fn with_in(left: &pb_type::Key, right: &pb_type::Value) -> Result<ElementFilter, ParseError> {
+    let right = pb_value_to_array_object(right);
+    match &left.item {
+        Some(pb_type::key::Item::Name(name)) => {
+            if let Some(right) = right {
+                Ok(contains_property(name.clone(), right))
+            } else {
+                unimplemented!()
```
Comment (longbinlai) [inline research/gaia/gremlin/gremlin_core/src/structure/filter/codec.rs:266]: and these unimplemented ones.

**Review by longbinlai — COMMENTED** [review]
Add the corresponding test case to verify if bugs have been fixed.

**Review by longbinlai — APPROVED** [review]
119/286 Gremlin test cases passed !!!
