### PR TITLE
fix(interactive): Fix bugs When Counting on Multiple Columns

### LINKED ISSUE #3410: feat(interactive): Support count multiple distinct column.
For the following query, compiler throw error`java.lang.UnsupportedOperationException: aggregate on multiple variables is unsupported yet`

```cypher
MATCH (p:Paper)-[:Resolve]->(ch:Challenge),
(p1:Paper)-[:Resolve]->(ch),
(p)-[c:Citation]-(p1)
RETURN COUNT(distinct p, p1)
```

### PR DESCRIPTION
**Pull request by shirly121**
## What do these changes do?
as titled.

## Related issue number

Fixes #3410

### CODE REVIEW

File: interactive_engine/compiler/src/test/java/com/alibaba/graphscope/common/ir/runtime/FfiLogicalPlanTest.java [hunk 1]
```diff
@@ -284,6 +284,23 @@ public void logical_plan_8_test() throws Exception {
         }
     }
 
+    @Test
+    public void logical_plan_9_test() throws Exception {
+        RelNode node =
+                com.alibaba.graphscope.cypher.antlr4.Utils.eval(
+                                "Match (a) Return count(distinct a.name, a.age)")
+                        .build();
+        System.out.println(node.getRowType());
```
Comment (longbinlai) [inline interactive_engine/compiler/src/test/java/com/alibaba/graphscope/common/ir/runtime/FfiLogicalPlanTest.java:293]: 尽量assert而不是print。

Comment (shirly121) [reply interactive_engine/compiler/src/test/java/com/alibaba/graphscope/common/ir/runtime/FfiLogicalPlanTest.java]: done in https://github.com/alibaba/GraphScope/pull/3442/commits/5bf01aa55b043b7c41c6baef4b3e57e7e8ed41e5

**Review by zhanglei1949 — APPROVED** [review]
LGTM

**Review by longbinlai — APPROVED** [review]
