### PR TITLE
[GAIA] add encode for single event

### LINKED ISSUE #368: [BUG] Encode for single event is unsupported
**Describe the bug**
Encode trait for a single event is unsupported, and is used in distributed execution.

**To Reproduce**
Gremlin query with `limit` operator triggering early-stop can trigger this bug in distributed execution.

### PR DESCRIPTION
**Pull request by youyangy**
## What do these changes do?

add encode for single event

## Related issue number
Fixes #368

### CODE REVIEW

File: research/gaia/pegasus/pegasus/src/event/io/mod.rs [hunk 1]
```diff
@@ -92,7 +92,10 @@ impl Encode for Events {
     fn write_to<W: WriteExt>(&self, writer: &mut W) -> ::std::io::Result<()> {
         match self {
             &Events::Batched(ref events) => events.write_to(writer),
-            _ => unimplemented!("[Unreachable]"),
+            &Events::Single(ref event) => {
```
Comment (longbinlai) [inline research/gaia/pegasus/pegasus/src/event/io/mod.rs:95]: You do not need to write `writer.write_u32()` for the Batched case? Otherwise how can you handle read. In addition, it looks like write_u8 is enough.

**Review by longbinlai — COMMENTED** [review]
Can you describe more for this bug fix? How this happen, and why the codes can fix the bug.

**Review by longbinlai — APPROVED** [review]
This has fixed the single-event issue related to early-stop signal.
