### PR TITLE
fix(interactive): Including primary keys when sinking vertex

### LINKED ISSUE #4433: [BUG] Primary key properties not returned.
When running cypher queries like `MATCH(n) return n`, the primary key property is not returned.

### PR DESCRIPTION
**Pull request by zhanglei1949**
Fix #4433

### CODE REVIEW

File: interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/fetcher/DynamicIrMetaFetcher.java [hunk 1]
```diff
@@ -81,7 +81,7 @@ private synchronized void syncMeta() {
             IrMeta meta = this.reader.readMeta();
             logger.debug(
                     "schema from remote: {}",
-                    (meta == null) ? null : meta.getSchema().getSchemaSpec(Type.IR_CORE_IN_JSON));
+                    (meta == null) ? null : meta.getSchema().getSchemaSpec(Type.FLEX_IN_JSON));
```
Comment (zhanglei1949) [inline interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/fetcher/DynamicIrMetaFetcher.java:84]: We need to use `FLEX_IN_JSON`, `IR_CORE_IN_JSON` doesn't support current data type system.

Comment (zhanglei1949) [reply interactive_engine/compiler/src/main/java/com/alibaba/graphscope/common/ir/meta/fetcher/DynamicIrMetaFetcher.java]: It seems that use FLEX_IN_JSON will cause other CI failure. This debug log is removed.

**Review by liulx20 — APPROVED** [review]

**Review by shirly121 — APPROVED** [review]
