### PR TITLE
fix(interactive): Support Multiple Matches in IR Core

### LINKED ISSUE #3052: [BUG] Incorrect Logical Plan Generated for Join of Multiple Matches in IR Core
**Describe the bug**
When attempting to perform a join of multiple matches using the IR Core FFI API, the logical plan generated is unexpected.

**To Reproduce**
Run the following java JNI codes to invoke FFI API provided by IR Core:
```java
Pointer ptrPlan = LIB.initLogicalPlan();

// append 'V()' operator
IntByReference oprScan = new IntByReference();
Pointer scan = LIB.initScanOperator(FfiScanOpt.Entity);
LIB.appendScanOperator(ptrPlan, scan, -1, oprScan);

// build sentence: as('a').out().as('b')
Pointer expand1 = LIB.initEdgexpdOperator(FfiExpandOpt.Vertex, FfiDirection.Out);
Pointer sentence1 = LIB.initPatternSentence(FfiJoinKind.Inner);
LIB.setSentenceStart(sentence1, ArgUtils.asNameOrId('a'));
LIB.addSentenceBinder(sentence1, expand1, FfiBinderOpt.Edge);
LIB.setSentenceEnd(sentence1, ArgUtils.asNameOrId('b'));

// add sentence to left match
IntByReference oprMatch1 = new IntByReference();
Pointer match1 = LIB.initPatternOperator();
LIB.addPatternSentence(match1, sentence1);
LIB.appendPatternOperator(ptrPlan, match1, oprScan.getValue(), oprMatch1);

// build sentence: as('c').out().as('b')
Pointer expand2 = LIB.initEdgexpdOperator(FfiExpandOpt.Vertex, FfiDirection.Out);
Pointer sentence2 = LIB.initPatternSentence(FfiJoinKind.Inner);
LIB.setSentenceStart(sentence2, ArgUtils.asNameOrId('c'));
LIB.addSentenceBinder(sentence2, expand2, FfiBinderOpt.Edge);
LIB.setSentenceEnd(sentence2, ArgUtils.asNameOrId('b'));

// add sentence to right match
IntByReference oprMatch2 = new IntByReference();
Pointer match2 = LIB.initPatternOperator();
LIB.addPatternSentence(match2, sentence2);
LIB.appendPatternOperator(ptrPlan, match2, oprScan.getValue(), oprMatch2);

// append join operator which left is match1, right is match2
IntByReference oprJoin = new IntByReference();
Pointer join = LIB.initJoinOperator(FfiJoinKind.Inner);
LIB.addJoinKeyPair(join, ArgUtils.asVar("b", ""), ArgUtils.asVar("b", ""));
LIB.appendJoinOperator(ptrPlan, join, oprMatch1.getValue(), oprMatch2.getValue(), oprJoin);

// append sink operator
LIB.appendSinkOperator(ptrPlan, LIB.initSinkOperator(), oprJoin.getValue(), new IntByReference());

System.out.println(LIB.printPlanAsJson(ptrPlan));
LIB.destroyLogicalPlan(ptrPlan);
```

**Screenshots**
match2 seems to be dropped:
```
FfiResult{code=Success, msg='{
  "nodes": [
    {
      "opr": {
        "opr": {
          "Scan": {
            "scan_opt": 0,
            "alias": {
              "item": {
                "Id": 97
              }
            },
            "params": {
              "tables": [],
              "columns": [],
              "is_all_columns": false,
              "limit": null,
              "predicate": null,
              "sample_ratio": 1.0,
              "extra": {}
            },
            "idx_predicate": null,
            "meta_data": null
          }
        }
      },
      "children": [
        1
      ]
    },
    {
      "opr": {
        "opr": {
          "Edge": {
            "v_tag": {
              "item": {
                "Id": 97
              }
            },
            "direction": 0,
            "params": {
              "tables": [],
              "columns": [],
              "is_all_columns": false,
              "limit": null,
              "predicate": null,
              "sample_ratio": 1.0,
              "extra": {}
            },
            "alias": null,
            "expand_opt": 1,
            "meta_data": null
          }
        }
      },
      "children": [
        2
      ]
    },
    {
      "opr": {
        "opr": {
          "Vertex": {
            "tag": null,
            "opt": 1,
            "params": null,
            "alias": {
              "item": {
                "Id": 98
              }
            },
            "meta_data": null
          }
        }
      },
      "children": []
    }
  ],
  "roots": []
}'}
```

### PR DESCRIPTION
**Pull request by BingqingLyu**
## What do these changes do?

As titled, support Multiple Matches in IR Core

1. From now, the logical plan will contain contain a dummy `RootScan` after initialization by default. This dummy `RootScan` may be later used to support multiple `scan`.
2. When a plan of a pattern matching is append to a node, if the plan is naive plan, it will directly append to the assigned node. Otherwise, it the plan is extend plan, then it must have its own scan operator, so it have to be append to the dummy `RootScan`
3. When a sink operator is append to the logical plan, it suggests that the logical plan building is finished. Therefore, it will call `clean_redundant_nodes` method to clean useless nodes. There are two kinds of reduandant nodes: `Scan `node with no child and dummy `RootScan` with zero or only single child.

## Related issue number

Fixes #3052 #3062

### CODE REVIEW

File: interactive_engine/executor/ir/core/src/plan/logical.rs [hunk 1]
```diff
@@ -1272,6 +1326,71 @@ impl AsLogical for pb::IndexPredicate {
...
+                    .entity_labels_iter()
+                    .map(|(_, label_id)| label_id)
+                    .collect();
+                params_label_ids.eq(&meta_label_ids)
+            }
+        } else {
+            false
+        }
+    } else {
+        false
```
Comment (BingqingLyu) [inline interactive_engine/executor/ir/core/src/plan/logical.rs:1376]: Even if store_meta is not provided, params.tables.is_empty() seems also indicates all_labels()?

File: interactive_engine/executor/ir/common/src/utils.rs [hunk 2]
```diff
@@ -589,23 +589,16 @@ impl From<(pb::EdgeExpand, pb::GetV)> for pb::path_expand::ExpandBase {
...
-                    scan.idx_predicate.is_none()
-                        && scan.alias.is_none()
-                        && scan
-                            .params
-                            .as_ref()
-                            .map(|params| !params.is_queryable())
-                            .unwrap_or(true)
-                }
-                _ => false,
+impl pb::LogicalPlan {
```
[the remark this answers is not in the document]
Comment (MeloYang05) [reply interactive_engine/executor/ir/common/src/utils.rs]: Fixed

File: interactive_engine/executor/ir/core/src/plan/logical.rs [hunk 3]
```diff
@@ -155,7 +168,7 @@ impl TryFrom<pb::LogicalPlan> for LogicalPlan {
                 return Err(ParsePbError::EmptyFieldError("Node::opr".to_string()));
             }
         }
-
+        plan.clean_redundant_nodes();
```
[the remark this answers is not in the document]
Comment (MeloYang05) [reply interactive_engine/executor/ir/core/src/plan/logical.rs:171]: Fixed, and edit a testcase

File: interactive_engine/executor/ir/core/src/plan/logical.rs [hunk 4]
```diff
@@ -416,8 +438,9 @@ impl LogicalPlan {
         if let Ok(store_meta) = STORE_META.read() {
             opr.preprocess(&store_meta, &mut self.meta)?;
         }
-        let new_curr_node_rst = match opr.opr.as_ref().unwrap() {
-            Opr::Pattern(pattern) => {
+
+        let new_curr_node_rst = match opr.opr.as_ref() {
```
[the remark this answers is not in the document]
Comment (MeloYang05) [reply interactive_engine/executor/ir/core/src/plan/logical.rs:442]: I think it is better to avoid unwrap in official code

File: interactive_engine/executor/ir/core/src/plan/logical.rs (hunk 1 above)
Comment (MeloYang05) [reply interactive_engine/executor/ir/core/src/plan/logical.rs:1376]: Fixed

File: interactive_engine/executor/ir/core/src/plan/logical.rs [hunk 5]
```diff
@@ -1272,6 +1328,71 @@ impl AsLogical for pb::IndexPredicate {
...
+                .entity_labels_iter()
+                .map(|(_, label_id)| label_id)
+                .collect();
+            params_label_ids.eq(&meta_label_ids)
+        } else {
+            false
+        }
+}
+
+fn is_node_dummy(node: &Node) -> bool {
```
Comment (longbinlai) [inline interactive_engine/executor/ir/core/src/plan/logical.rs:1382]: The `pb` type should take the whole `pb` inheritance, such as `pb::logical_plan::operator::` ..

File: interactive_engine/executor/ir/proto/algebra.proto [hunk 6]
```diff
@@ -469,6 +469,9 @@ message SinkVineyard {
   schema.Schema graph_schema = 2;
 }
 
+// A dummy node to delegate a source opr for multiple scan cases.
+message RootScan {}
```
Comment (longbinlai) [inline interactive_engine/executor/ir/proto/algebra.proto:473]: Do not like `RootScan`, Simply call it `Root`.

File: interactive_engine/executor/ir/core/src/plan/logical.rs (hunk 5 above)
Comment (BingqingLyu) [reply interactive_engine/executor/ir/core/src/plan/logical.rs]: Done.

File: interactive_engine/executor/ir/proto/algebra.proto (hunk 6 above)
Comment (BingqingLyu) [reply interactive_engine/executor/ir/proto/algebra.proto]: Done.

**Review by longbinlai — APPROVED** [review]
LGTM

**Review by shirly121 — APPROVED** [review]
