### PR TITLE
fix(interactive): fix bugs when try to get labels or properties from an None entry

### LINKED ISSUE #4340: [BUG] GIE fails in fetch properties after optional match
**Describe the bug**

**To Reproduce**

The below example runs fails in GIE-Insight, on LDBC dataset:

```
@neo4j> MATCH (country:PLACE {name: "India"})<-[:ISPARTOF]-(:PLACE)<-[:ISLOCATEDIN]-(zombie:PERSON)
                                        OPTIONAL MATCH (zombie)<-[:HASCREATOR]-(message)
                                        WHERE message.creationDate < 20100630000000000
        return country limit 1;
com.alibaba.graphscope.common.exception.ExecutionException:
ErrorCode: JobExecuteIoError
EC: 04-0213
Message: "system error: kind(IOError), caused by:IOError(kind=System(NotConnected))
```

### PR DESCRIPTION
**Pull request by BingqingLyu**
## What do these changes do?

As titled.

## Related issue number

Fixes #4340

### CODE REVIEW

File: interactive_engine/executor/ir/graph_proxy/src/apis/graph/element/property.rs [hunk 1]
```diff
@@ -44,40 +44,44 @@ impl PropKey {
...
-                    })
-                    .unwrap_or(Object::None),
-                PropKey::Key(key) => {
-                    if let Some(prop_val) = graph_element.get_property(key) {
-                        prop_val.try_to_owned().ok_or_else(|| {
-                            ExprEvalError::OtherErr("cannot get `Object` from `BorrowObject`".to_string())
-                        })?
-                    } else {
-                        Object::None
+            if let Some(graph_element) = element.as_graph_element() {
```
Comment (longbinlai) [inline interactive_engine/executor/ir/graph_proxy/src/apis/graph/element/property.rs:47]: Fix the implementation such that calling as_graph_element() from an None object can return a special object that have implementation of getting None value from any properties?

File: interactive_engine/executor/ir/runtime/src/process/operator/map/get_v.rs [hunk 2]
```diff
@@ -158,7 +158,8 @@ impl FilterMapFunction<Record, Record> for AuxiliaOperator {
             //     then we set tag=None and alias="a" in auxilia
 
             // 1. If to filter by labels, and the entry itself carries label information already, directly eval it without query the store
-            if self.query_params.has_labels() && entry.label().is_some() {
+            if self.query_params.has_labels() && entry.as_graph_path().is_some() && entry.label().is_some()
```
Comment (longbinlai) [inline interactive_engine/executor/ir/runtime/src/process/operator/map/get_v.rs:161]: Fix this if condition when verifying the special implementation for None object.

Comment (BingqingLyu) [reply interactive_engine/executor/ir/runtime/src/process/operator/map/get_v.rs]: Done.

File: interactive_engine/executor/ir/graph_proxy/src/apis/graph/element/property.rs (hunk 1 above)
Comment (BingqingLyu) [reply interactive_engine/executor/ir/graph_proxy/src/apis/graph/element/property.rs]: Done. Introduced a `NullGraphEntry' for a null graph element.

File: interactive_engine/executor/ir/runtime/src/process/entry.rs [hunk 3]
```diff
@@ -51,6 +52,8 @@ pub enum EntryType {
     Intersection,
     /// Type of collection consisting of entries
     Collection,
+    /// A Null graph element entry type
+    NullGraphType,
```
Comment (longbinlai) [inline interactive_engine/executor/ir/runtime/src/process/entry.rs:56]: `Null` or `NullEntity` is a better name. Because in other items, you did not say VertexType, or EdgeType,

File: interactive_engine/executor/ir/runtime/src/process/entry.rs [hunk 4]
```diff
@@ -548,6 +559,49 @@ impl Decode for CollectionEntry {
     }
 }
 
+#[derive(Debug, Clone, Default, PartialEq, PartialOrd, Eq, Hash)]
+pub struct NullGraphEntry;
+
+impl_as_any!(NullGraphEntry);
+
+impl Entry for NullGraphEntry {
```
Comment (longbinlai) [inline interactive_engine/executor/ir/runtime/src/process/entry.rs:567]: `NullEntry` is fine.

File: interactive_engine/executor/ir/runtime/src/process/entry.rs (hunk 3 above)
Comment (BingqingLyu) [reply interactive_engine/executor/ir/runtime/src/process/entry.rs]: Done.

File: interactive_engine/executor/ir/runtime/src/process/entry.rs (hunk 4 above)
Comment (BingqingLyu) [reply interactive_engine/executor/ir/runtime/src/process/entry.rs]: Done.

File: interactive_engine/executor/ir/graph_proxy/src/apis/graph/mod.rs [hunk 5]
```diff
@@ -30,6 +30,8 @@ use crate::utils::expr::eval_pred::PEvaluator;
 
 pub mod element;
 pub type ID = i64;
+// a special id for Null graph elements.
+pub const NULL_ID: ID = ID::MAX;
```
[the remark this answers is not in the document]
Comment (BingqingLyu) [reply interactive_engine/executor/ir/graph_proxy/src/apis/graph/mod.rs:34]: No, we don't have one.

**Review by longbinlai — APPROVED** [review]

**Review by shirly121 — APPROVED** [review]
