### PR TITLE
Enhancement of build.sh

### LINKED ISSUE #264: [BUG] enhancement of standalone building process
**Describe the bug**
- Currently, the `build.sh` is in-compatible with macOS;
- it doesn't check whether the tools is available in the local env.

**Additional context**
Suggestions:
- if it doesn't support mac or windows, prevent users use it on these platforms.
- check all the commands (like `mvn`, `cargo`.....) used in the script at the beginning. redirect to prepare_env.sh if the env doesn't satisfy the requirement.

### PR DESCRIPTION
**Pull request by siyuan0322**
Fixes #264 .

### CODE REVIEW

**Review by sighingnow — APPROVED** [review]

File: scripts/build.sh [hunk 1]
```diff
@@ -3,9 +3,85 @@
...
+    exit 1
+  fi
+  if ! command -v cargo &> /dev/null; then
+      echo "cargo ${err_msg}"
+      exit
+  fi
+  if ! command -v go &> /dev/null; then
+      echo "go ${err_msg}"
+      exit
+  fi
```
Comment (acezen) [inline scripts/build.sh:82]: maybe check `git` and `cmake` too.

**Review by yecol — APPROVED** [review]

**Review by acezen — APPROVED** [review]
