### PR TITLE
[GAIA-IR] Fix compiling warnings in v6d_ffi

### LINKED ISSUE #1779: [GIE-GAIA/IR] Please fix compiling warnings
After the latest pr, it starts prompting a lot of compiling warnings related to v6d_ffi, just like the following fragments:
```
warning: unused variable: `si`
    --> v6d_ffi/src/read_ffi.rs:1099:16
     |
1099 |         &self, si: i64, labels_ref: &Vec<LabelId>, condition: Option<&Condition>,
     |                ^^ help: if this is intentional, prefix it with an underscore: `_si`
warning: unused variable: `condition`
    --> v6d_ffi/src/read_ffi.rs:1099:52
     |
1099 |         &self, si: i64, labels_ref: &Vec<LabelId>, condition: Option<&Condition>,
     |                                                    ^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_condition`
```

### PR DESCRIPTION
**Pull request by BingqingLyu**
## What do these changes do?

As titled.

## Related issue number

Fixes #1779

### CODE REVIEW

File: research/query_service/ir/v6d_ffi/build.rs [hunk 1]
```diff
@@ -56,7 +51,7 @@ fn codegen_inplace() -> Result<(), Box<dyn std::error::Error>> {
 
     if cfg!(target_os = "linux") {
         println!("cargo:rustc-link-lib=mpi_cxx");
-        if Path::new("/usr/ali/alicpp/built/gcc-4.9.2").exists() {
+        if std::path::Path::new("/usr/ali/alicpp/built/gcc-4.9.2").exists() {
```
Comment (longbinlai) [inline research/query_service/ir/v6d_ffi/build.rs:54]: This is very hack~~

Comment (sighingnow) [reply research/query_service/ir/v6d_ffi/build.rs:54]: Can be removed, as alicpp (4.9.2) is no longer our target platform.

**Review by sighingnow — APPROVED** [review]
