### PR TITLE
Print metrics of application running time

### LINKED ISSUE #2898: The analytical algorithm performance doesn't meet the expectation
I tested pagerank and sssp algorithm on GraphScope and Gemini. And found that the Gemini performed much faster than the GraphScope. Here is the result of **pagerank** test with the dataset of **soc-LiveJournal1** . The iterations is **20**:

| platform  | time usage |
| ------------- | ------------- |
| GraphScope  | 1.4s |
| Gemini | 0.37s  |
| Libgrape-lite |   0.15s|

The script of GraphScope
```
import graphscope
import time
import datetime

sess = graphscope.session(num_workers=1, cluster_type='hosts')

graph = sess.g()

start = time.time()
graph = graph.add_edges('../data_set/live_journal/soc-livejournal.csv', src_label='v', dst_label='v', properties = [])
end = time.time()

print("Loading time: %f" % (end - start))

start = time.time()
ret1 = graphscope.pagerank(graph, max_round = 20)
end = time.time()

print("Running time: %f" % (end - start))

print(ret1.to_dataframe(selector={'id': 'v.id', 'label': 'r'}))

sess.close()
```
The command of running libgrape-lite
`mpirun -n 1 ./run_app --vfile ../../data_set/live_journal/soc-livejournal.vertex.csv --efile ../../data_set/live_journal/soc-livejournal.mtx --application pagerank --out_prefix ./output_pagerank --directed -pr_mr 20`

The running command of Gemini
`./toolkits/pagerank ./data_set/live_journal/soc-livejournal.binarye 4033137 20`

Each of the above three tests sets one partition.

The problem is that the graphscope is 10 times worse than the libgrape-lite. I don't know if my test script is wrong, please advise. Thanks!

### PR DESCRIPTION
**Pull request by siyuan0322**
Fixes #2898

### CODE REVIEW

File: analytical_engine/core/app/app_invoker.h [hunk 1]
```diff
@@ -16,13 +16,14 @@
...
-#include <glog/logging.h>
-
 #include <cstdint>
 #include <memory>
 #include <string>
 #include <type_traits>
 
+#include "glog/logging.h"
+#include "grape/util.h"
+
```
Comment (sighingnow) [inline analytical_engine/core/app/app_invoker.h:26]: Nice catch!

File: analytical_engine/core/app/app_invoker.h [hunk 2]
```diff
@@ -186,15 +187,18 @@ class AppInvoker {
   static void query_impl(std::shared_ptr<worker_t> worker,
                          const rpc::QueryArgs& query_args,
                          std::index_sequence<I...>) {
+    double t0 = grape::GetCurrentTime();
```
Comment (sighingnow) [inline analytical_engine/core/app/app_invoker.h:190]: t0/t1 to start_time/end_time would be better.

File: analytical_engine/core/app/app_invoker.h [hunk 3]
```diff
@@ -186,15 +187,18 @@ class AppInvoker {
...
     worker->Query(
         ArgsUnpacker<typename std::remove_const<typename std::remove_reference<
             typename ArgTypeAt<I + 1, context_init_func_t>::type>::type>::
                          type>::unpack(query_args.args(I))...);
+    double t1 = grape::GetCurrentTime();
+    LOG(INFO) << "Query time: " << t1 - t0;
```
Comment (sighingnow) [inline analytical_engine/core/app/app_invoker.h:196]: Adding the unit for less confusing:

LOG(INFO) << "Query time: " << t1 - t0 << " seconds";

**Review by sighingnow — APPROVED** [review]
